version: '3.8'

services:
  db:
    image: postgres:13
    container_name: my_database
    environment:
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_db
    volumes:
      - ./backend/pkg/db/docker-compose.yaml:/docker-entrypoint-initdb.d/init.sql
      - ./ml/bases:/app/ml/bases
      - ./ml/models:/app/ml/models
    ports:
      - "5432:5432"
    networks:
      - my_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: go_backend
    volumes:
      - ./backend:/app
      - ./ml/models:/app/ml/models
      - ./ml/bases:/app/ml/bases
    ports:
      - "8090:8090"
    environment:
      - DB_HOST=db
      - DB_USER=your_user
      - DB_PASSWORD=your_password
      - DB_NAME=your_db
    depends_on:
      - db
    networks:
      - my_network

  python_server:
    build:
      context: .
      dockerfile: ml/Dockerfile
    container_name: python_server
    volumes:
      - ./ml:/app/ml
    ports:
      - "5000:5000"
    environment:
      - MODEL_PATH=/app/ml/models
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  ml_models:
    driver: local
  ml_bases:
    driver: local
