version: '3.8'
services:
  postgres:
    image: postgres:14  
    container_name: postgres_container
    environment:
      POSTGRES_USER: username  
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: mydatabase  
    ports:
      - "5432:5432"  
    volumes:
      - pg_data:/var/lib/postgresql/data  
volumes:
  pg_data: